# Generated by Django 6.0.7 on 2026-07-22 10:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyBackup",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="keybackup",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blob",
                    core.fields.OpaqueBlobField(
                        bucket_set=[4096, 16384, 65536, 262144, 1048576]
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.BigIntegerField()),
                (
                    "blob",
                    core.fields.OpaqueBlobField(
                        bucket_set=[1024, 4096, 16384, 65536, 262144]
                    ),
                ),
                ("stored_date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "seq"), name="uq_history_owner_seq"
                    )
                ],
            },
        ),
    ]
