# Generated by Django 6.0.7 on 2026-09-04 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyBackup",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="keybackup",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blob",
                    core.fields.OpaqueBlobField(
                        bucket_set=[4096, 16384, 65536, 262144, 1048576]
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
