# Generated by Django 6.0.7 on 2026-07-25 05:51

from django.db import migrations


class Migration(migrations.Migration):
    """DESTRUCTIVE on a real deployment: drops vault_historyrecord and every
    encrypted history record in it. Server-side history is removed by design —
    history now transfers client-to-client on new-device enrollment — but rows
    deleted here are unrecoverable, so deploying this migration is the point of
    no return for any history not already held on a client device."""

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historyrecord',
            name='uq_history_owner_seq',
        ),
        migrations.DeleteModel(
            name='HistoryRecord',
        ),
    ]
