# Generated by Django 6.0.7 on 2026-07-21 12:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ik_pub", models.BinaryField()),
                ("spk_id", models.PositiveIntegerField()),
                ("spk_pub", models.BinaryField()),
                ("spk_sig", models.BinaryField()),
                ("spk_updated_date", models.DateField(auto_now_add=True)),
                ("registration_id", models.PositiveIntegerField()),
                (
                    "label_blob",
                    core.fields.OpaqueBlobField(bucket_set=[256, 1024], null=True),
                ),
                ("token_generation", models.PositiveIntegerField(default=1)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("last_active_date", models.DateField(null=True)),
                ("revoked_date", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blob", core.fields.OpaqueBlobField(bucket_set=[2048, 8192])),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_packages",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OneTimePrekey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.PositiveIntegerField()),
                ("pub", models.BinaryField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onetime_prekeys",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "key_id"),
                        name="uniq_onetimeprekey_device_key_id",
                    )
                ],
            },
        ),
    ]
