# Generated by Django 6.0.7 on 2026-09-04 14:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="identity",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("master_pub", models.BinaryField()),
                ("self_signing_pub", models.BinaryField()),
                ("user_signing_pub", models.BinaryField()),
                ("master_sig", models.BinaryField()),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ik_pub", models.BinaryField()),
                ("spk_id", models.PositiveIntegerField()),
                ("spk_pub", models.BinaryField()),
                ("spk_sig", models.BinaryField()),
                ("spk_updated_date", models.DateField(auto_now_add=True)),
                ("registration_id", models.PositiveIntegerField()),
                ("cross_sig", models.BinaryField(null=True)),
                ("bundle_version", models.PositiveIntegerField(default=0)),
                (
                    "label_blob",
                    core.fields.OpaqueBlobField(bucket_set=[256, 1024], null=True),
                ),
                ("token_generation", models.PositiveIntegerField(default=1)),
                ("refresh_generation", models.PositiveIntegerField(default=1)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("last_active_date", models.DateField(null=True)),
                ("revoked_date", models.DateField(null=True)),
                ("queue_seq", models.BigIntegerField(default=0)),
                ("queue_pruned_through", models.BigIntegerField(default=0)),
                ("pq_spk_id", models.PositiveIntegerField(null=True)),
                ("pq_spk_pub", models.BinaryField(null=True)),
                ("pq_spk_sig", models.BinaryField(null=True)),
                ("pq_spk_updated_date", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceLogRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.BigIntegerField()),
                ("blob", core.fields.OpaqueBlobField(bucket_set=[256, 1024])),
                ("stored_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "seq"), name="uq_devicelog_user_seq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OneTimePrekey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.PositiveIntegerField()),
                ("pub", models.BinaryField()),
                (
                    "device",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onetime_prekeys",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "key_id"),
                        name="uniq_onetimeprekey_device_key_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PqOneTimePrekey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.PositiveIntegerField()),
                ("pub", models.BinaryField()),
                (
                    "device",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pq_onetime_prekeys",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "key_id"),
                        name="uniq_pq_onetimeprekey_device_key_id",
                    )
                ],
            },
        ),
    ]
