# Generated by Django 6.0.7 on 2026-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="queue_seq",
            field=models.BigIntegerField(default=0),
        ),
    ]
