# Generated by Django 6.0.7 on 2026-07-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0003_alter_onetimeprekey_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identity', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('master_pub', models.BinaryField()),
                ('self_signing_pub', models.BinaryField()),
                ('user_signing_pub', models.BinaryField()),
                ('master_sig', models.BinaryField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='bundle_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='cross_sig',
            field=models.BinaryField(null=True),
        ),
    ]
