# Generated by Django 6.0.7 on 2026-07-25 05:38

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_useridentity_device_bundle_version_device_cross_sig"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="pq_spk_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="pq_spk_pub",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="pq_spk_sig",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="pq_spk_updated_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="keypackage",
            name="blob",
            field=core.fields.OpaqueBlobField(bucket_set=[4096, 16384]),
        ),
        migrations.CreateModel(
            name="PqOneTimePrekey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.PositiveIntegerField()),
                ("pub", models.BinaryField()),
                (
                    "device",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pq_onetime_prekeys",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "key_id"),
                        name="uniq_pq_onetimeprekey_device_key_id",
                    )
                ],
            },
        ),
    ]
