# Generated by Django 6.0.7 on 2026-07-25 05:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_device_pq_spk_id_device_pq_spk_pub_device_pq_spk_sig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLogRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.BigIntegerField()),
                ("blob", core.fields.OpaqueBlobField(bucket_set=[256, 1024])),
                ("stored_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "seq"), name="uq_devicelog_user_seq"
                    )
                ],
            },
        ),
    ]
