# Generated by Django 6.0.7 on 2026-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_devicelogrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="queue_pruned_through",
            field=models.BigIntegerField(default=0),
        ),
    ]
