# Generated by Django 6.0.7 on 2026-07-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """From this phase on, registration requires cross_sig, bundle_version, and
    (past the account's first device) a published identity. Devices that existed
    before cross-signing landed keep cross_sig = NULL: nothing is backfilled or
    auto-generated — the server holds no key that could sign anything, and a
    fabricated signature would be worse than none. Such devices are surfaced to
    peers as unverified (cross_sig: null) until the client re-enrolls them."""

    dependencies = [
        ('devices', '0007_device_queue_pruned_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypackage',
            name='is_last_resort',
            field=models.BooleanField(default=False),
        ),
    ]
