# Generated by Django 6.0.7 on 2026-07-21 17:33

import core.fields
import django.db.models.deletion
import messaging.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_queue_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('blob', core.fields.OpaqueBlobField(bucket_set=[1024, 4096, 16384, 65536, 262144])),
                ('queued_hour', models.DateTimeField(default=messaging.models._truncate_hour, editable=False)),
                ('recipient_device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='devices.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient_device', 'seq'), name='uq_queue_device_seq')],
            },
        ),
    ]
