# Generated by Django 6.0.7 on 2026-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import attachments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=attachments.models._new_capability_id,
                        editable=False,
                        max_length=43,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
