# Generated by Django 6.0.7 on 2026-09-04 14:13

import uuid

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_blob", core.fields.OpaqueBlobField(bucket_set=[256, 1024])),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
