# Generated by Django 6.0.7 on 2026-09-05 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voicerooms", "0001_initial"),
    ]

    operations = [
        # `DROP TABLE voicerooms_room`, which takes ACCESS EXCLUSIVE on that table
        # and blocks every read and write of it until the migration commits. It is
        # a catalogue change and not a scan, so the hold is milliseconds however
        # many rows the table has — but the lock still queues behind any open
        # transaction that has touched the table, and everything after it queues
        # behind the lock. Free here: ADR-0021 removed every reader and writer of
        # the table in the same release, and the deployment stops the service
        # before it migrates (`ops/RUNBOOK.md` §5), so the only session that can
        # name the relation is this one.
        #
        # Reversing this re-creates an empty table. The rows are not recoverable
        # from the migration, and none exist: the deployment is pre-launch and
        # `docs/architecture/GROUND-TRUTH.md` records no production database.
        migrations.DeleteModel(
            name="Room",
        ),
    ]
